package com.vanzstuff.readdit.data;

import android.content.ContentUris;
import android.net.Uri;
import android.provider.BaseColumns;

import com.vanzstuff.readdit.Logger;

/**
 * App contract
 */
public class ReadditContract {

    public static final String CONTENT_AUTHORITY = "com.vanzstuff.readdit.provider";
    public static final Uri BASE_CONTENT_URI = Uri.parse("content://" + CONTENT_AUTHORITY);
    public static final String PATH_TAG = "tag";
    public static final String PATH_POST = "post";
    public static final String PATH_POST_BY_TAG = "post_tag" ;
    public static final String PATH_POST_BY_TAGID = "post_tagid" ;
    public static final String PATH_ADD_TAG_TO_POST = "post_add_tag";
    public static final String PATH_ADD_TAG_NAME_TO_POST = "post_add_tag_name";
    public static final String PATH_COMMENT = "comment";
    public static final String PATH_SUBREDDIT = "subreddit";
    public static final String PATH_USER = "user";
    public static final String PATH_VOTE = "vote";
    public static final String MULTIPLE_ITEM_MIMETYPE = "vnd.android.cursor.dir/";
    public static final String SINGLE_ITEM_MIMETYPE = "vnd.android.cursor.item/";


    /**
     * table stores all tags created by the user
     */
    public static final class Tag implements BaseColumns{

        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_TAG).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE + CONTENT_AUTHORITY + "/" + PATH_TAG;

        public static Uri buildTagUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        /**
         * Get the tag ID from the Uri generated by buildTagUri
         * @param uri uri generated by buildTagUri
         * @return -1 if could not retrieve the the id. Otherwise, return the id
         */
        public static long getTagId(Uri uri){
            if ( uri.getPathSegments().size() == 2)
                return Long.parseLong(uri.getPathSegments().get(1));
            return -1l;
        }

        public static final String TABLE_NAME = "tag";
        public static final String COLUMN_NAME = "name";
    }

    /**
     * table stores all post tagged/saved by the user
     */
    public static final class Post implements BaseColumns{

        /** Uri used to retrieve all post */
        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_POST).build();
        public static final Uri CONTENT_URI_POST_BY_TAG = BASE_CONTENT_URI.buildUpon().appendPath(PATH_POST_BY_TAG).build();
        public static final Uri CONTENT_URI_POST_BY_TAGID = BASE_CONTENT_URI.buildUpon().appendPath(PATH_POST_BY_TAGID).build();
        public static final Uri CONTENT_URI_ADD_TAG_TO_POST = BASE_CONTENT_URI.buildUpon().appendPath(PATH_ADD_TAG_TO_POST).build();
        public static final Uri CONTENT_URI_ADD_TAG_NAME_TO_POST = BASE_CONTENT_URI.buildUpon().appendPath(PATH_ADD_TAG_NAME_TO_POST).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE +  CONTENT_AUTHORITY + "/" + PATH_POST;
        public static final String CONTENT_TYPE_POST_BY_TAG = MULTIPLE_ITEM_MIMETYPE +  CONTENT_AUTHORITY + "/" + PATH_POST_BY_TAG;


        /**
         * Build a Uri with the last segment of the path is the post ID
         * @param id
         * @return uri with the post ID
         */
        public static Uri buildPostUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        /**
         * Get the post ID from the Uri generated by buildPostUri
         * @param uri uri generated by buildPostUri
         * @return -1 if could not retrieve the the id. Otherwise, return the id
         */
        public static long getPostId(Uri uri){
            if ( uri.getPathSegments().size() == 2)
                return Long.parseLong(uri.getPathSegments().get(1));
            return -1l;
        }

        /**
         * Build a uri to retrieve the post from a given tag
         * @param tag used to retrieve the posts
         * @return Uri to retrieve the posts
         */
        public static Uri buildPostByTagUri(String tag){
            return CONTENT_URI_POST_BY_TAG.buildUpon().appendPath(tag).build();
        }
        
        /**
         * Get the tag from Uri created by the method buildPostByTagUri
         * @param uri that holds the tag
         * @return tag retrieved
         */
        static String getTagFromUri(Uri uri){
            return uri.getPathSegments().get(2);
        }

        /**
         * Build the Uri used to add the given tagID to the given postID
         * @param postID
         * @param tagID
         * @return
         */
        public static Uri buildAddTagUri(long postID, long tagID){
            return CONTENT_URI_ADD_TAG_TO_POST.buildUpon()
                    .appendPath(String.valueOf(postID))
                    .appendPath(String.valueOf(tagID)).build();
        }

        public static Uri buildAddTagUri(long postID, String tag){
            return CONTENT_URI_ADD_TAG_NAME_TO_POST.buildUpon()
                    .appendPath(String.valueOf(postID))
                    .appendPath(String.valueOf(tag)).build();
        }

        /**
         * Method used to get the tag and post ids from the Uri generate by buildAddTagUri method
         * @param uri generated by buildAddTagUri
         * @return long[] where the first position contains the post id and the second one the tag
         * id
         */
        public static long[] getTagIdAndPostIdFromUri(Uri uri){
            return new long[]{
                    Long.parseLong(uri.getPathSegments().get(1)),
                    Long.parseLong(uri.getPathSegments().get(2))
            };
        }

        /**
         * Method used to get the tag and post ids from the Uri generate by buildAddTagUri method
         * @param uri generated by buildAddTagUri
         * @return String[] where the first position contains the post id and the second one the tag
         * id
         */
        public static String[] getTagNameFromUri(Uri uri){
            return new String[]{
                    uri.getPathSegments().get(1),
                    uri.getPathSegments().get(2)
            };
        }

        /**
         * Build a uri to retrieve the post from a given tag id
         * @param tagId id used to retrieve the posts
         * @return Uri to retrieve the posts
         */
        public static Uri buildPostByTagIdUri(long tagId){
            return CONTENT_URI_POST_BY_TAGID.buildUpon().appendPath(String.valueOf(tagId)).build();
        }

        /**
         * Get the tag from Uri created by the method buildPostByTagIdUri
         * @param uri that holds the tag
         * @return tag retrieved
         */
        static String getTagIdFromUri(Uri uri){
            return uri.getPathSegments().get(1);
        }

        public static final String TABLE_NAME = "post";
        public static final String COLUMN_TITLE = "title";
        public static final String COLUMN_SUBREDDIT = "subreddit";
        public static final String COLUMN_CONTENT = "content";
        public static final String COLUMN_USER = "user";
        public static final String COLUMN_VOTES = "votes";
        public static final String COLUMN_THREADS = "threads";
        public static final String COLUMN_DATE = "date";
        public static final String COLUMN_CONTENT_TYPE = "content_type";
    }

    public static final class TagXPost implements BaseColumns{
        public static final String TABLE_NAME = "tag_x_post";
        public static final String COLUMN_TAG = "tag";
        public static final String COLUMN_POST = "post";
    }

    /**
     * Table stores all comments ( and its parents ) saved by the user
     */
    public static final class Comment implements BaseColumns{
        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_COMMENT).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE + CONTENT_AUTHORITY + "/" + PATH_COMMENT;

        public static Uri buildCommentUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        /**
         * Get the user ID from the Uri generated by buildCommentUri
         * @param uri uri generated by buildCommentUri
         * @return -1 if could not retrieve the the id. Otherwise, return the id
         */
        public static long getCommentId(Uri uri){
            if ( uri.getPathSegments().size() == 2)
                return Long.parseLong(uri.getPathSegments().get(1));
            return -1l;
        }

        public static final String TABLE_NAME = "comment";
        public static final String COLUMN_PARENT = "parent";
        public static final String COLUMN_CONTENT = "content";
        public static final String COLUMN_USER = "user";
        public static final String COLUMN_POST = "post";
        public static final String COLUMN_DATE = "date";
    }

    /**
     * Table stores all user subscribes
     */
    public static final class Subreddit implements BaseColumns{
        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_SUBREDDIT).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE + CONTENT_AUTHORITY + "/" + PATH_SUBREDDIT;

        public static Uri buildSubscribeUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        public static final String TABLE_NAME = "subreddit";
        /**
         * number of users active in last 15 minutes
         * Type: integer
         */
        public static final String COLUMN_ACCOUNTS_ACTIVE = "accounts_active";
        /**
         * number of minutes the subreddit initially hides comment scores
         * Type: integer
         */
        public static final String COLUMN_COMMENT_SCORE_HIDE_MINS= "comment_score_hide_mins";
        /**
         * sidebar text
         * Type: text
         */
        public static final String COLUMN_DESCRIPTION = "description";
        /**
         * sidebar text, escaped HTML format
         * Type: text
         */
        public static final String COLUMN_DESCRIPTION_HTML = "description_html";
        /**
         * human name of the subreddit
         * Type: text
         */
        public static final String COLUMN_DISPLAY_NAME = "display_name";
        /**
         * full URL to the header image
         * Type: text
         */
        public static final String COLUMN_HEADER_IMG = "header_img";
        /**
         * width of the header image
         * Type: integer
         */
        public static final String COLUMN_HEADER_WIDTH = "header_width";
        /**
         * height of the header image
         * Type: integer
         */
        public static final String COLUMN_HEADER_HEIGHT = "header_height";
        /**
         * description of header image shown on hover
         * Type: text
         */
        public static final String COLUMN_HEADER_TITLE = "header_title";
        /**
         * is_nsfw?
         * Type: integer
         */
        public static final String COLUMN_OVER18 = "over18";
        /**
         * Description shown in subreddit search results?
         * Type: text
         */
        public static final String COLUMN_PUBLIC_DESCRIPTION = "public_description";
        /**
         * whether the subreddit's traffic page is publicly-accessible
         * Type: integer
         */
        public static final String COLUMN_PUBLIC_TRAFFIC = "public_traffic";
        /**
         * the number of redditors subscribed to this subreddit
         * Type: integer
         */
        public static final String COLUMN_SUBSCRIBERS = "subscribers";
        /**
         * the type of submissions the subreddit allows - one of "any", "link" or "self"
         * Type: text
         */
        public static final String COLUMN_SUBMISSION_TYPE = "submission_type";
        /**
         * the subreddit's custom label for the submit link button, if any
         * Type: text
         */
        public static final String COLUMN_SUBMIT_LINK_LABEL = "submit_link_label";
        /**
         * the subreddit's custom label for the submit text button, if any
         * Type: text
         */
        public static final String COLUMN_SUBMIT_TEXT_LABEL = "submit_text_label";
        /**
         * the subreddit's type - one of "public", "private", "restricted", or in very special cases "gold_restricted" or "archived"
         * Type: text
         */
        public static final String COLUMN_SUBREDDIT_TYPE = "subreddit_type";
        /**
         * title of the main page
         * Type: text
         */
        public static final String COLUMN_TITLE = "title";
        /**
         * The relative URL of the subreddit. Ex: "/r/pics/"
         * Type: text
         */
        public static final String COLUMN_URL = "url";
        /**
         * whether the logged-in user is banned from the subreddit
         * Type: integer
         */
        public static final String COLUMN_USER_IS_BANNED= "user_is_banned";
        /**
         * whether the logged-in user is an approved submitter in the subreddit
         * Type: integer
         */
        public static final String COLUMN_USER_IS_CONTRIBUTOR = "user_is_contributor";
        /**
         * whether the logged-in user is a moderator of the subreddit
         * Type: interger
         */
        public static final String COLUMN_USER_IS_MODERATOR = "user_is_moderator";
        /**
         * whether the logged-in user is subscribed to the subreddit
         * Type: integer
         */
        public static final String COLUMN_USER_IS_SUBSCRIBER = "user_is_subscriber";
        /**
         * Type: text
         */
        public static final String COLUMN_SUBMIT_TEXT_HTML = "submit_text_html";
        /**
         * Type: text
         */
        public static final String COLUMN_ID = "id";
        /**
         * Type: text
         */
        public static final String COLUMN_SUBMIT_TEXT = "submit_text";
        /**
         * Type: integer
         */
        public static final String COLUMN_COLLAPSE_DELETED_COMMENTS = "collapse_deleted_comments";
        /**
         * Type: text
         */
        public static final String COLUMN_PUBLIC_DESCRIPTION_HTML = "public_description_html";
        /**
         * Type: text
         */
        public static final String COLUMN_NAME = "name";
        /**
         * Type: integer
         */
        public static final String COLUMN_CREATED = "created";
        /**
         * Type: integer
         */
        public static final String COLUMN_CREATED_UTC = "created_utc";
        /**
         * user subscribed in the subreddit
         * Type: integer
         */
        public static final String COLUMN_USER = "user";
        /**
         * synchronization status
         * Type: integer
         */
        public static final String COLUMN_SYNC_STATUS = "sync_status";

    }

    /**
     * Table stores the votes of the user
     */
    public static final class Vote implements BaseColumns{
        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_VOTE).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE + CONTENT_AUTHORITY + "/" + PATH_VOTE;
        public static final String TABLE_NAME = "vote";
        /**
         * The post voted
         * Type: long
         */
        public static final String COLUMN_POST = "post";
        /**
         * The user that has voted in the post
         * Type: long
         */
        public static final String COLUMN_USER = "user";
        /**
         * The direction of the vote ( up or down )
         * Type: int
         */
        public static final String COLUMN_DIRECTION = "direction";


        public static Uri buildVoteUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        /**
         * Get the vote ID from the Uri generated by buildVoteUri
         * @param uri uri generated by buildVoteUri
         * @return -1 if could not retrieve the the id. Otherwise, return the id
         */
        public static long getVoteId(Uri uri){
            if ( uri.getPathSegments().size() == 2)
                return Long.parseLong(uri.getPathSegments().get(1));
            return -1l;
        }
    }

    /**
     * Table stores the the users
     */
    public static final class User implements BaseColumns{
        public static final Uri CONTENT_URI = BASE_CONTENT_URI.buildUpon().appendPath(PATH_USER).build();
        public static final String CONTENT_TYPE = MULTIPLE_ITEM_MIMETYPE + CONTENT_AUTHORITY + "/" + PATH_USER;
        public static final String TABLE_NAME = "user";
        /**
         * The username of the account in question.
         * This attribute overrides the superclass's name attribute. Do not confuse an account's name which is
         * the account's username with a thing's name which is the thing's FULLNAME.
         * See API: Glossary for details on what FULLNAMEs are
         * Type: string
         */
        public static final String COLUMN_NAME = "name";
        /**
         * The curent user's access token
         * Type: string
         */
        public static final String COLUMN_ACCESSTOKEN = "access_token";
        /**
         * Flag idicate if the user is the current user
         * Type: boolean
         */
        public static final String COLUMN_CURRENT = "current";
        /**
         * whether the logged-in user has this user set as a friend
         * Type: integer
         */
        public static final String COLUMN_IS_FRIEND = "is_friend";
        /**
         * Type:
         */
        public static final String COLUMN_GOLD_EXPIRATION = "gold_expiration";
        /**
         * current modhash. not present if not your account
         * Type: text
         */
        public static final String COLUMN_MODHASH = "modhash";
        /**
         * user has provided an email address and got it verified?
         * Type: integer
         */
        public static final String COLUMN_HAS_VERIFIED_EMAIL = "has_verified_email";
        /**
         * Type: integer
         */
        public static final String COLUMN_CREATED_UTC = "created_utc";
        /**
         * Type: boolean
         */
        public static final String COLUMN_HIDE_FROM_ROBOTS = "hide_from_robots";
        /**
         * user's comment karma
         * Type: integer
         */
        public static final String COLUMN_COMMENT_KARMA = "comment_karma";
        /**
         * whether this account is set to be over 18
         * Type: integer
         */
        public static final String COLUMN_OVER_18 = "over_18";
        /**
         * Type: integer
         */
        public static final String COLUMN_GOLD_CREDDITS = "gold_creddits";
        /**
         * Type: integer
         */
        public static final String COLUMN_CREATED = "created";
        /**
         * reddit gold status
         * Type: integer
         */
        public static final String COLUMN_IS_GOLD = "is_gold";
        /**
         * whether this account moderates any subreddits
         * Type: integer
         */
        public static final String COLUMN_IS_MOD = "is_mod";
        /**
         * user's link karma
         * Type: integer
         */
        public static final String COLUMN_LINK_KARMA = "link_karma";
        /**
         * ID of the account; prepend t2_ to get fullname
         * Type: text
         */
        public static final String COLUMN_ID = "id";
        /**
         * user has unread mail? null if not your account
         * Type: integer
         */
        public static final String COLUMN_HAS_MAIL = "has_mail";
        /**
         * user has unread mod mail? null if not your account
         * Type: integer
         */
        public static final String COLUMN_HAS_MOD_MAIL = "has_mod_mail";
        /**
         * Type: integer
         */
        public static final String COLUMN_SYNC_STATUS = "sync_status";



        public static Uri buildUserUri(long id){
            return ContentUris.withAppendedId(CONTENT_URI, id);
        }

        /**
         * Get the vote ID from the Uri generated by buildUserUri
         * @param uri uri generated by buildUserUri
         * @return -1 if could not retrieve the the id. Otherwise, return the id
         */
        public static long getUserId(Uri uri){
            return ContentUris.parseId(uri);
        }
    }
}
